default: &default
  adapter: mysql2
  host: localhost # Override where needed
  database: bitla_flash_way  # Override where needed
  port: 3306
  username: root
  password: bitla@123
  encoding: utf8
  reconnect: false
  pool: 5
  # socket: /tmp/mysql.sock
  # min_messages: ERROR 

development:
  <<: *default